services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=media_recyclarr_dev
      - POSTGRES_PASSWORD=media_recyclarr_dev
      - POSTGRES_DB=media_recyclarr_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}