# https://api-docs.overseerr.dev/
### Get requests - Available
GET {{ uri }}/api/v1/request?filter=available&take=40
X-Api-Key: {{ api_key }}

### Get requests - All
GET {{ uri }}/api/v1/request?take=40
X-Api-Key: {{ api_key }}

### Get tv
GET {{ uri }}/api/v1/tv/125
X-Api-Key: {{ api_key }}