/*
Emby Server REST API (BETA)

Testing DynamicHlsServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package embyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Noah-Huppert/media-recyclarr/embyclient"
)

func Test_embyclient_DynamicHlsServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DynamicHlsServiceAPIService GetAudioByIdHls1ByPlaylistidBySegmentidBySegmentcontainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentContainer string
		var segmentId string
		var id string
		var playlistId string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetAudioByIdHls1ByPlaylistidBySegmentidBySegmentcontainer(context.Background(), segmentContainer, segmentId, id, playlistId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetAudioByIdMainM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetAudioByIdMainM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetAudioByIdMasterM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetAudioByIdMasterM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetVideosByIdHls1ByPlaylistidBySegmentidBySegmentcontainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentContainer string
		var segmentId string
		var id string
		var playlistId string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetVideosByIdHls1ByPlaylistidBySegmentidBySegmentcontainer(context.Background(), segmentContainer, segmentId, id, playlistId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetVideosByIdLiveSubtitlesM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetVideosByIdLiveSubtitlesM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetVideosByIdMainM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetVideosByIdMainM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetVideosByIdMasterM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetVideosByIdMasterM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService GetVideosByIdSubtitlesM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.GetVideosByIdSubtitlesM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService HeadAudioByIdHls1ByPlaylistidBySegmentidBySegmentcontainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentContainer string
		var segmentId string
		var id string
		var playlistId string

		httpRes, err := apiClient.DynamicHlsServiceAPI.HeadAudioByIdHls1ByPlaylistidBySegmentidBySegmentcontainer(context.Background(), segmentContainer, segmentId, id, playlistId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService HeadAudioByIdMasterM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.HeadAudioByIdMasterM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService HeadVideosByIdHls1ByPlaylistidBySegmentidBySegmentcontainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentContainer string
		var segmentId string
		var id string
		var playlistId string

		httpRes, err := apiClient.DynamicHlsServiceAPI.HeadVideosByIdHls1ByPlaylistidBySegmentidBySegmentcontainer(context.Background(), segmentContainer, segmentId, id, playlistId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicHlsServiceAPIService HeadVideosByIdMasterM3u8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.DynamicHlsServiceAPI.HeadVideosByIdMasterM3u8(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
